name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  PC_HASH: placeholder

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync
      - name: Set PC_HASH for pre-commit cache key
        run: echo "PC_HASH=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - name: Cache pre-commit hooks
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PC_HASH }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: uv run pre-commit run -v --all-files --show-diff-on-failure --color=always

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Python 3.13
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: |
          if find tests -type f | grep -q .; then
            uv run pytest --cov --cov-branch --cov-report=xml
          else
            exit 0
          fi
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: morsznetik/pyPlayer
